---
- name: Execute ping command
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    hostname: "{{ tower_webhook_payload.ping_hostname }}"
    duration: "{{ tower_webhook_payload.ping_duration }}"

  tasks:
    - name: Ping host
      command: ping -c {{ duration }} {{ hostname }}
      register: ping_result

    - name: Display ping output
      debug:
        msg: "{{ ping_result.stdout_lines }}"
